name: Grammar and Spell Check

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install language-tool-python

      - name: Check for .py and .yaml changes
        id: check_changes
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '\.(py|yaml)$' || true)
          echo "::set-output name=changed_files::$changed_files"

      - name: Run grammar and spell check
        if: steps.check_changes.outputs.changed_files != ''
        run: |
          changed_files=${{ steps.check_changes.outputs.changed_files }}
          echo "$changed_files" | while read file; do
            python -c "
import language_tool_python

tool = language_tool_python.LanguageTool('en-US')

with open('${file}', 'r') as f:
    content = f.read()

matches = tool.check(content)
for match in matches:
    print(f'{file}: {match}')
"
          done
        shell: bash
